### ISSUE TITLE
color of white space

### ISSUE THREAD

**Issue by t7yang** [licatajustin/sierra-syntax#1]
make white space visible so that developer can know the indentation level when fold code with hotkey (ctrl-k, num). thx
![2016-12-16_100047](https://cloud.githubusercontent.com/assets/4502661/21249124/e2fea876-c376-11e6-9f4b-b0e0ffeb261f.png)

**Comment by licatajustin** [comment]
Thanks for reporting this, I'll look into this today.

**Comment by licatajustin** [comment]
Fixed in `v0.1.2`.
