### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by mihaliak** [licatajustin/sierra-syntax#2]
Hey man, what font is used in screenshot? It would be great to add it to readme because it looks sick!

Thanks.

**Comment by licatajustin** [comment]
It is a really nice font! It's called [Operator Mono](https://www.typography.com/blog/introducing-operator), which is priced at around $200 for about 10 styles, however, there are also free alternatives, like [Fira Code + flottflott](https://medium.com/@docodemore/an-alternative-to-operator-mono-font-6e5d040e1c7e). I used the alternatives for a few months before deciding to buy the license.

If you'd like to submit a PR to add a link in the README to the typography.com website I linked to above, I'd welcome it.

Cheers @mihaliak ❤️
